// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class UpdateRound {
  static encode(message: UpdateRound, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(18);
    writer.string(message.startDate);

    writer.uint32(26);
    writer.string(message.endDate);
  }

  static decode(reader: Reader, length: i32): UpdateRound {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new UpdateRound();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.startDate = reader.string();
          break;

        case 3:
          message.endDate = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  startDate: string;
  endDate: string;

  constructor(id: string = "", startDate: string = "", endDate: string = "") {
    this.id = id;
    this.startDate = startDate;
    this.endDate = endDate;
  }
}
